### ISSUE TITLE
Erros on build

### ISSUE THREAD

**Issue by radudiaconu0** [rigor789/nativescript-vue-next#373]
It gives me this errors when i build the template with ns preview
```
Error: [copy-webpack-plugin] patterns must be an array
    at new CopyWebpackPlugin (C:\Users\radu0\Desktop\New folder\myVue3App\node_modules\copy-webpack-plugin\dist\index.js:22:15)
    at module.exports (C:\Users\radu0\Desktop\New folder\myVue3App\webpack.config.js:354:7)
    at handleFunction (C:\Users\radu0\Desktop\New folder\myVue3App\node_modules\webpack-cli\bin\utils\prepareOptions.js:21:13)
    at prepareOptions (C:\Users\radu0\Desktop\New folder\myVue3App\node_modules\webpack-cli\bin\utils\prepareOptions.js:9:5)
    at requireConfig (C:\Users\radu0\Desktop\New folder\myVue3App\node_modules\webpack-cli\bin\utils\convert-argv.js:117:14)
    at C:\Users\radu0\Desktop\New folder\myVue3App\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\radu0\Desktop\New folder\myVue3App\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at C:\Users\radu0\Desktop\New folder\myVue3App\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\Users\radu0\Desktop\New folder\myVue3App\node_modules\yargs\yargs.js:576:18)
    at C:\Users\radu0\Desktop\New folder\myVue3App\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Users\radu0\Desktop\New folder\myVue3App\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\radu0\Desktop\New folder\myVue3App\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```
This is my package.json
```
"dependencies": {
    "@nativescript/core": "^7.2.0",
    "nativescript-vue": "3.0.0-dev.4"
  },
  "devDependencies": {
    "@babel/core": "^7.12.13",
    "@babel/preset-env": "^7.12.13",
    "@nativescript-vue/compiler": "3.0.0-dev.4",
    "@nativescript/android": "7.0.1",
    "@nativescript/webpack": "^4.1.0",
    "babel-loader": "^8.2.2",
    "sass": "^1.32.6",
    "vue-loader": "^16.1.2"
  },
```

Also it gives me an error when i try composition api ;P

**Comment by rigor789** [comment]
Use `@nativescript/webpack` `^3.0.0` for now, that should work!

**Comment by radudiaconu0** [comment]
@rigor789 i wondered If it's possible a vitejs implementation for nativescript:))
